<a href="https://colab.research.google.com/github/LaraDondossola/Estatistica_aplicada/blob/main/Implementa%C3%A7%C3%A3o_Python_estatistica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

matriz = np.array([[1,2,3],[4,5,6]])

resultado = matriz * 2

print("Normal:\n", matriz)
print("\nMultiplicado por 2:\n", resultado)


Normal:
 [[1 2 3]
 [4 5 6]]

Multiplicado por 2:
 [[ 2  4  6]
 [ 8 10 12]]


In [ ]:
import pandas as pd
from pandas import Series
from pandas import DataFrame

obj = Series([4,7,-5,3])

obj #fomando a Series visualmente (em matriz)

type(obj) #para ver o tipo de objeto que está usando

obj.values #para verificar os valores que estão dentro do objeto

obj.index #mostra os índices, começo, fim, percorre os índices de 1 em 1



RangeIndex(start=0, stop=4, step=1)

In [ ]:
obj2 = Series([4,7,-5,3], index = ['a', 'b', 'c', 'd'])

obj2

obj2.values

obj2.index

obj2[obj2>3] #somente maior que 3

obj2['b'] #vai buscar por posição específica

'd' in obj2 #perguntar se a posição 'd' existe

True

In [ ]:
dict = {'futebol':5200, 'tenis':120, 'natação':698,  'volleyball':150}

obj3 = Series(dict)

obj3

futebol       5200
tenis          120
natação        698
volleyball     150
dtype: int64

In [ ]:
esportes = ['futebol', 'tenis', 'natação','basketball']

obj4 = Series(dict, index = esportes)

obj4

pd.isnull(obj4)

pd.notnull(obj4)

futebol        True
tenis          True
natação        True
basketball    False
dtype: bool

In [ ]:
obj3 + obj4 #soma pelos índices

basketball        NaN
futebol       10400.0
natação        1396.0
tenis           240.0
volleyball        NaN
dtype: float64

In [ ]:
obj4.name = 'população'
obj4.index.name = 'esporte'

obj4

esporte
futebol       5200.0
tenis          120.0
natação        698.0
basketball       NaN
Name: população, dtype: float64

In [ ]:
from pandas import DataFrame

data = {'estado': ['Santa Catarina', 'Paraná', 'Goiás', 'Bahia', 'Minas Gerais'],
        'ano': [2002,2003,2004,2005,2006],
        'população':[1.5,1.7,3.6,2.4,2.9]}

frame = DataFrame(data)

type(frame)

frame


estado   ano  população
0  Santa Catarina  2002        1.5
1          Paraná  2003        1.7
2           Goiás  2004        3.6
3           Bahia  2005        2.4
4    Minas Gerais  2006        2.9

In [ ]:
#para mudanças no formato, mudar as colunas, PROVA

DataFrame(data, columns= ['ano', 'estado', 'população'])

ano          estado  população
0  2002  Santa Catarina        1.5
1  2003          Paraná        1.7
2  2004           Goiás        3.6
3  2005           Bahia        2.4
4  2006    Minas Gerais        2.9

In [ ]:
#para criar um frame maior

frame2 = DataFrame(data, columns= ['ano', 'estado','população', 'débito'], index = ['um', 'dois', 'três', 'quatro', 'cinco'])

frame2

ano          estado  população débito
um      2002  Santa Catarina        1.5    NaN
dois    2003          Paraná        1.7    NaN
três    2004           Goiás        3.6    NaN
quatro  2005           Bahia        2.4    NaN
cinco   2006    Minas Gerais        2.9    NaN

In [ ]:
#imprmir somente uma coluna

frame2['estado']

um        Santa Catarina
dois              Paraná
três               Goiás
quatro             Bahia
cinco       Minas Gerais
Name: estado, dtype: object