<a href="https://colab.research.google.com/github/LaraDondossola/Estatistica_aplicada/blob/main/Implementa%C3%A7%C3%A3o_Python_estatistica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**AULA 3**



In [ ]:
import numpy as np

matriz = np.array([[1,2,3],[4,5,6]])

resultado = matriz * 2

print("Normal:\n", matriz)
print("\nMultiplicado por 2:\n", resultado)


Normal:
 [[1 2 3]
 [4 5 6]]

Multiplicado por 2:
 [[ 2  4  6]
 [ 8 10 12]]


In [ ]:
import pandas as pd
from pandas import Series
from pandas import DataFrame

obj = Series([4,7,-5,3])

obj #fomando a Series visualmente (em matriz)

type(obj) #para ver o tipo de objeto que está usando

obj.values #para verificar os valores que estão dentro do objeto

obj.index #mostra os índices, começo, fim, percorre os índices de 1 em 1



RangeIndex(start=0, stop=4, step=1)

In [ ]:
obj2 = Series([4,7,-5,3], index = ['a', 'b', 'c', 'd'])

obj2

obj2.values

obj2.index

obj2[obj2>3] #somente maior que 3

obj2['b'] #vai buscar por posição específica

'd' in obj2 #perguntar se a posição 'd' existe

True

In [ ]:
dict = {'futebol':5200, 'tenis':120, 'natação':698,  'volleyball':150}

obj3 = Series(dict)

obj3

futebol       5200
tenis          120
natação        698
volleyball     150
dtype: int64

In [ ]:
esportes = ['futebol', 'tenis', 'natação','basketball']

obj4 = Series(dict, index = esportes)

obj4

pd.isnull(obj4)

pd.notnull(obj4)

futebol        True
tenis          True
natação        True
basketball    False
dtype: bool

In [ ]:
obj3 + obj4 #soma pelos índices

basketball        NaN
futebol       10400.0
natação        1396.0
tenis           240.0
volleyball        NaN
dtype: float64

In [ ]:
obj4.name = 'população'
obj4.index.name = 'esporte'

obj4

esporte
futebol       5200.0
tenis          120.0
natação        698.0
basketball       NaN
Name: população, dtype: float64

In [ ]:
from pandas import DataFrame

data = {'estado': ['Santa Catarina', 'Paraná', 'Goiás', 'Bahia', 'Minas Gerais'],
        'ano': [2002,2003,2004,2005,2006],
        'população':[1.5,1.7,3.6,2.4,2.9]}

frame = DataFrame(data)

type(frame)

frame


estado   ano  população
0  Santa Catarina  2002        1.5
1          Paraná  2003        1.7
2           Goiás  2004        3.6
3           Bahia  2005        2.4
4    Minas Gerais  2006        2.9

In [ ]:
#para mudanças no formato, mudar as colunas, PROVA

DataFrame(data, columns= ['ano', 'estado', 'população'])

ano          estado  população
0  2002  Santa Catarina        1.5
1  2003          Paraná        1.7
2  2004           Goiás        3.6
3  2005           Bahia        2.4
4  2006    Minas Gerais        2.9

In [ ]:
#para criar um frame maior

frame2 = DataFrame(data, columns= ['ano', 'estado','população', 'débito'], index = ['um', 'dois', 'três', 'quatro', 'cinco'])

frame2

ano          estado  população débito
um      2002  Santa Catarina        1.5    NaN
dois    2003          Paraná        1.7    NaN
três    2004           Goiás        3.6    NaN
quatro  2005           Bahia        2.4    NaN
cinco   2006    Minas Gerais        2.9    NaN

In [ ]:
#imprmir somente uma coluna

frame2['estado']

um        Santa Catarina
dois              Paraná
três               Goiás
quatro             Bahia
cinco       Minas Gerais
Name: estado, dtype: object

#**AULA 4**

In [ ]:
frame2['débito'] = np.arange(5.)
frame2
frame2.values

array([[2002, 'Santa Catarina', 1.5, 0.0],
       [2003, 'Paraná', 1.7, 1.0],
       [2004, 'Goiás', 3.6, 2.0],
       [2005, 'Bahia', 2.4, 3.0],
       [2006, 'Minas Gerais', 2.9, 4.0]], dtype=object)

In [ ]:
frame2.describe()

ano  população    débito
count     5.000000   5.000000  5.000000
mean   2004.000000   2.420000  2.000000
std       1.581139   0.864292  1.581139
min    2002.000000   1.500000  0.000000
25%    2003.000000   1.700000  1.000000
50%    2004.000000   2.400000  2.000000
75%    2005.000000   2.900000  3.000000
max    2006.000000   3.600000  4.000000

In [ ]:
frame2.dtypes

ano            int64
estado        object
população    float64
débito       float64
dtype: object

In [ ]:
frame2.index ##o que faz isso aqui? PROVA// Como faço para exibir as colunas no meio da frame?

Index(['um', 'dois', 'três', 'quatro', 'cinco'], dtype='object')

In [ ]:
frame2[:3]

ano          estado  população  débito
um    2002  Santa Catarina        1.5     0.0
dois  2003          Paraná        1.7     1.0
três  2004           Goiás        3.6     2.0

In [ ]:
web_status = {'Dias': [1, 2, 3, 4, 5, 6,7],
              'Visitantes':[ 45, 23, 67, 78, 23, 12, 14],
              'Taxas': [11, 22, 33, 44, 55, 66, 77]} #dicionário com 3 pares de valores

df = pd.DataFrame(web_status) #criando o DataFrame
print(df) #imprimindo dicionário

   Dias  Visitantes  Taxas
0     1          45     11
1     2          23     22
2     3          67     33
3     4          78     44
4     5          23     55
5     6          12     66
6     7          14     77


In [ ]:
df #diferença de imprimir com print ou só o df:
   #print(df) - somente mostrar informação para o usuário
   #df - conseguimos manipular os dados e as extensões

Dias  Visitantes  Taxas
0     1          45     11
1     2          23     22
2     3          67     33
3     4          78     44
4     5          23     55
5     6          12     66
6     7          14     77

In [ ]:
print(df.set_index('Dias')) #tornando a coluna 'Dias' como índice
#se manipular o dado com print, o dado não altera de verdade, se fizesse sem o print, ele iria alterar

      Visitantes  Taxas
Dias                   
1             45     11
2             23     22
3             67     33
4             78     44
5             23     55
6             12     66
7             14     77


In [ ]:
print(df.head())

   Dias  Visitantes  Taxas
0     1          45     11
1     2          23     22
2     3          67     33
3     4          78     44
4     5          23     55


In [ ]:
print(df['Visitantes']) #imprimir só a coluna visitantes do DataFrame

0    45
1    23
2    67
3    78
4    23
5    12
6    14
Name: Visitantes, dtype: int64


In [ ]:
print(df[['Visitantes', 'Taxas']]) #imprimindo duas colunas

   Visitantes  Taxas
0          45     11
1          23     22
2          67     33
3          78     44
4          23     55
5          12     66
6          14     77
